name: Android Build Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package_name:
        description: '输入要修改的包名'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: 安装JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adoptopenjdk'

      - name: 安装Apktool
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: 下载SignApk工具
        run: |
          wget https://github.com/appium/signapk/releases/download/v1.0/signapk.jar -O signapk.jar

      - name: 普通编译
        if: github.event_name == 'push'
        run: ./build.sh

      - name: 特殊编译（带包名）
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.package_name != ''
        run: ./build.sh -s "${{ github.event.inputs.package_name }}"

      - name: 上传APK产物
        uses: actions/upload-artifact@v4  # 升级到v4
        if: success()
        with:
          name: apk-artifacts
          path: app/build/outputs/apk/
          retention-days: 30  # 可选：设置保留30天
