name: Android Build Workflow

on:
  # 触发条件：推送到main分支或手动触发
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package_name:
        description: '输入要修改的包名'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest  # 使用Linux环境（与原命令兼容）
    
    steps:
      - name: 克隆代码
        uses: actions/checkout@v3

      - name: 安装JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adoptopenjdk'

      - name: 安装Apktool（通过APT）
        run: |
          sudo apt-get update
          sudo apt-get install -y apktool

      - name: 下载SignApk工具
        run: |
          # 从GitHub仓库下载预编译的signapk（需提前确认可用链接）
          wget https://github.com/appium/signapk/releases/download/v1.0/signapk.jar -O signapk.jar

      - name: 执行普通编译
        if: github.event_name == 'push'
        run: |
          ./build.sh

      - name: 执行特殊编译（带包名参数）
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.package_name != ''
        run: |
          ./build.sh -s "${{ github.event.inputs.package_name }}"

      - name: 上传编译产物（可选）
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: apk-artifacts
          path: app/build/outputs/apk/
